/**
 * Author:
 *   Jennifer Hernandez Becares
 *   Luis Maria Costero Valero
 * Doble Grado en Ing. Informática-Matemáticas
 * Curso 2013/2014 - PLG
*/


//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Jun 02 15:30:48 CEST 2014
//----------------------------------------------------

package plg.aSint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int NUMERO = 47;
  public static final int DISTINTO = 13;
  public static final int POT = 26;
  public static final int MULT = 23;
  public static final int CHAR = 29;
  public static final int DOS_PUNTOS = 6;
  public static final int INT = 27;
  public static final int PAR_ABRE = 8;
  public static final int IDENTIFICADOR = 46;
  public static final int IS = 43;
  public static final int NOT = 20;
  public static final int AND = 14;
  public static final int IGUAL = 7;
  public static final int OR = 15;
  public static final int ENDDEFPROC = 41;
  public static final int BOOL = 30;
  public static final int CALL = 49;
  public static final int BEGIN = 48;
  public static final int DIV = 24;
  public static final int IF = 31;
  public static final int DEFSTRUCT = 38;
  public static final int ENDWHILE = 37;
  public static final int PUNTO_COMA = 4;
  public static final int IGUAL_IGUAL = 12;
  public static final int DEFPROC = 40;
  public static final int EOF = 0;
  public static final int RETURN = 50;
  public static final int TRUE = 51;
  public static final int error = 1;
  public static final int COMA = 5;
  public static final int MENOS = 22;
  public static final int MENOR = 18;
  public static final int ENDSTRUCT = 44;
  public static final int MOD = 25;
  public static final int VOID = 28;
  public static final int MAYOR = 16;
  public static final int ENDIF = 34;
  public static final int ELSE = 33;
  public static final int PUNTO = 3;
  public static final int WHILE = 35;
  public static final int MAYOR_IGUAL = 17;
  public static final int THEN = 32;
  public static final int ENDDEFSTRUCT = 39;
  public static final int END = 2;
  public static final int CORCH_ABRE = 10;
  public static final int PAR_CIERRE = 9;
  public static final int MENOR_IGUAL = 19;
  public static final int FALSE = 52;
  public static final int STRUCT = 42;
  public static final int PROCEDURE = 45;
  public static final int DO = 36;
  public static final int CORCH_CIERRE = 11;
  public static final int MAS = 21;
}

